trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: TerraformInstaller@1
  inputs:
    terraformVersion: latest

- task: TerraformTaskV4@4
  displayName: Terraform Init
  inputs:
    provider: azurerm
    command: init
    backendServiceArm: azure-sc

- task: TerraformTaskV4@4
  displayName: Terraform Validate
  inputs:
    provider: azurerm
    command: validate

- task: TerraformTaskV4@4
  displayName: Terraform Plan
  inputs:
    provider: azurerm
    command: plan
    environmentServiceNameAzureRM: azure-sc

- task: TerraformTaskV4@4
  displayName: Terraform Apply
  inputs:
    provider: azurerm
    command: apply
    environmentServiceNameAzureRM: azure-sc
